### ISSUE TITLE
CMake install not relocatable via `CMAKE_INSTALL_PREFIX`

### ISSUE THREAD

**Issue by Faaux** [zlib-ng/minizip-ng#575]
Hey everyone,

The current CMakeLists set the default install path based on
```cmake
set(INSTALL_BIN_DIR ${CMAKE_INSTALL_FULL_BINDIR} CACHE PATH "Installation directory for executables")
set(INSTALL_LIB_DIR ${CMAKE_INSTALL_FULL_LIBDIR} CACHE PATH "Installation directory for libraries")
set(INSTALL_INC_DIR ${CMAKE_INSTALL_FULL_INCLUDEDIR} CACHE PATH "Installation directory for headers")
set(INSTALL_MAN_DIR ${CMAKE_INSTALL_FULL_MANDIR} CACHE PATH "Installation directory for manual pages")
```
this does not account for changes in the `CMAKE_INSTALL_PREFIX` and can lead to issues when installing.

I stumbled across this when I tried to use the VCPKG integration which results in non relocatable packages since the generated `minizip-ng.cmake` has an absolute `_IMPORT_PREFIX`.

Suggested solution (from https://github.com/madler/zlib/blob/v1.2.11/CMakeLists.txt):
```cmake
set(INSTALL_BIN_DIR "${CMAKE_INSTALL_PREFIX}/bin" CACHE PATH "Installation directory for executables")
set(INSTALL_LIB_DIR "${CMAKE_INSTALL_PREFIX}/lib" CACHE PATH "Installation directory for libraries")
set(INSTALL_INC_DIR "${CMAKE_INSTALL_PREFIX}/include" CACHE PATH "Installation directory for headers")
set(INSTALL_MAN_DIR "${CMAKE_INSTALL_PREFIX}/share/man" CACHE PATH "Installation directory for manual pages")
```

Cheers

**Comment by nmoinvaz** [comment]
I think this was recently fixed in #569.

**Comment by Faaux** [comment]
Thanks, I will try with the updated VCPKG ports, was still on 3.0.1. Will reopen if not fixed
